[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61", "typing_extensions; python_version < '3.12'"]

[dependency-groups]
dev = [
  "covdefaults>=2.1.0",
  "coverage",
  "pytest",
]

[project]
authors = [{name = "Max R", email = "mxr@users.noreply.github.com"}]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
description = "pre-commit mirror for pyright with vendored node and npm"
dynamic = ["version"]
keywords = ["pyright", "pre-commit", "mirror", "node", "npm"]
license = "MIT"
license-files = ["LICENSE"]
name = "mirrors-pyright"
readme = "README.md"
requires-python = ">=3.11"

[project.scripts]
pyright = "mirrors_pyright.__main__:main"

[project.urls]
Homepage = "https://github.com/mxr/mirrors-pyright"

[tool.coverage.run]
plugins = ["covdefaults"]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
disallow_untyped_defs = false
module = "tests.*"

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-select = [
  "A",  # see flake8-builtins
  "B",  # see flake8-bugbear
  "C4",  # see flake8-comprehension
  "I",  # sort imports
  "SIM",  # see flake8-simplify
  "TC",  # see flake8-type-checking
  "UP",  # see pyupgrade
]

[tool.ruff.lint.isort]
force-single-line = true
required-imports = ["from __future__ import annotations"]

[tool.setuptools.dynamic]
version = {attr = "mirrors_pyright.__version__"}

[tool.setuptools.package-data]
mirrors_pyright = ["_vendor/**/*", "py.typed"]

[tool.setuptools.packages.find]
include = ["mirrors_pyright*"]

[tool.tox]
env_list = ["py", "pre-commit"]

[tool.tox.env.pre-commit]
commands = [["pre-commit", "run", "--all-files", "--show-diff-on-failure"]]
deps = ["pre-commit-uv"]
skip_install = true

[tool.tox.env_run_base]
commands = [
  ["coverage", "erase"],
  ["coverage", "run", "-m", "pytest", "{posargs:tests}"],
  ["coverage", "report"],
]
dependency_groups = ["dev"]

[tool.ty.rules]
all = "error"
